// src/client/src/systems/achtung/config/archetypes.js
// Données complètes des archétypes (bonus attr/skill, focus pool, talent pool, équipement).
// Les clés de talentPool référencent TALENTS (./talents.js).

export const ARCHETYPE_DATA = {
    boffin: {
        label: 'Boffin',
        labelFr: 'Expert',
        tagline: 'Le cerveau du groupe. Si un Expert ne sait pas quelque chose, il peut probablement le découvrir.',
        playIf: [
            'Être le plus intelligent du groupe.',
            'Avoir une réponse à tout.',
            'Craquer des codes, désactiver des chars, et déjouer les nazis !',
        ],
        description: 'Un Expert sait comment les choses fonctionnent. Il possède de vastes connaissances techniques et pratiques, et le talent pour les mettre en œuvre. Si un Boffin ne sait pas quelque chose, il peut probablement le découvrir à force d\'essais et d\'erreurs — et il n\'a pas peur de se salir les mains.',
        attrBonus:   { brawn: 1, coordination: 2, insight: 1, reason: 2 },
        skillBonus:  { academia: 1, engineering: 2, medicine: 2, observation: 1, stealth: 1, vehicles: 2 },
        focusPool:   ['engineering', 'medicine', 'vehicles'],
        focusCount:  2,
        talentPool:  ['prototype', 'lifesaver', 'push_the_limits'],
        belongings:  [
            'Outils de mécanicien ou un contact (mécanicien)',
            'Outils d\'électricien ou un contact (électricien)',
            'Kit de démolition ou un contact (explosifs)',
            'Trousse médicale ou un contact (médecine)',
        ],
        belongingsNote: 'Choisissez deux kits d\'outils, deux contacts, ou un kit et un contact.',
    },
    commander: {
        label: 'Commander',
        labelFr: 'Commandant',
        tagline: 'Le chef tactique. Maître des troupes et des ressources, toujours capable de voir le tableau d\'ensemble.',
        playIf: [
            'Être le chef du groupe.',
            'Donner des ordres et aider les autres.',
            'Mener la charge avec des tactiques audacieuses pour atteindre l\'objectif !',
        ],
        description: 'Les balles, les baïonnettes et les bombes ne sont utiles que si elles sont déployées au bon endroit au bon moment. Un Commandant est passé maître dans cet art, capable de voir le tableau d\'ensemble et de rassembler troupes et ressources pour que chacun puisse faire son travail avec une efficacité maximale.',
        attrBonus:   { coordination: 2, insight: 1, reason: 2, will: 1 },
        skillBonus:  { academia: 1, fighting: 2, persuasion: 1, survival: 2, stealth: 1, tactics: 2 },
        focusPool:   ['fighting', 'survival', 'tactics'],
        focusCount:  2,
        talentPool:  ['opportunist', 'wilderness_guide', 'born_leader'],
        belongings:  [],
        belongingsNote: 'Au début de chaque aventure, vous pouvez réquisitionner gratuitement un objet de Restriction 2 ou moins.',
    },
    con_artist: {
        label: 'Con Artist',
        labelFr: 'Escroc',
        tagline: 'Le manipulateur. Habile à intimider, séduire, persuader et tromper pour parvenir à ses fins.',
        playIf: [
            'Avoir une personnalité magnétique.',
            'Duper vos ennemis et porter d\'incroyables déguisements.',
            'Manipuler votre cible, berner les gardes, ou se cacher en plein jour !',
        ],
        description: 'Un Escroc est dans son élément en société, parlant toutes les langues et adoptant tous les traits de personnalité nécessaires pour arriver à ses fins. Ce sont des manipulateurs habiles, capables d\'intimider, séduire, persuader et tromper pour traverser la vie — tout aussi doués pour repérer quand quelqu\'un d\'autre essaie de les manipuler.',
        attrBonus:   { coordination: 1, insight: 2, reason: 1, will: 2 },
        skillBonus:  { academia: 1, observation: 2, persuasion: 2, resilience: 1, stealth: 2, tactics: 1 },
        focusPool:   ['observation', 'persuasion', 'stealth'],
        focusCount:  2,
        talentPool:  ['cold_reading', 'a_way_with_words', 'chameleon'],
        belongings:  ['Kit de déguisement', 'Un contact (n\'importe quelle compétence ou focus)'],
        belongingsNote: '',
    },
    grease_monkey: {
        label: 'Grease Monkey',
        labelFr: 'Mécano',
        tagline: 'L\'expert en véhicules. Virtuellement né derrière un volant, précieux sur les missions dangereuses.',
        playIf: [
            'Être expert en véhicules.',
            'Construire ou réparer à peu près n\'importe quoi.',
            'Piloter des avions, opérer de l\'artillerie, et prendre en chasse les nazis !',
        ],
        description: 'Virtuellement né derrière un volant, vous êtes un expert pour amener personnes et fournitures là où elles doivent être. Vous êtes irremplaçable lors des missions dangereuses, non seulement pour votre capacité à opérer des véhicules, mais pour votre talent à les maintenir en état de marche dans les pires conditions.',
        attrBonus:   { brawn: 1, coordination: 2, insight: 1, reason: 2 },
        skillBonus:  { athletics: 1, engineering: 2, persuasion: 2, resilience: 1, survival: 1, vehicles: 2 },
        focusPool:   ['engineering', 'persuasion', 'vehicles'],
        focusCount:  2,
        talentPool:  ['keep_it_steady', 'quartermaster', 'born_to_drive'],
        belongings:  ['Outils de mécanicien', 'Un contact (Véhicules)'],
        belongingsNote: '',
    },
    infiltrator: {
        label: 'Infiltrator',
        labelFr: 'Infiltré',
        tagline: 'L\'ombre. Expert pour entrer là où il ne devrait pas être, éviter la détection et récupérer des secrets.',
        playIf: [
            'Faire la guerre depuis les ombres !',
            'Se glisser derrière les lignes ennemies.',
            'Se déplacer sans être vu et être là où vous ne devriez pas !',
        ],
        description: 'Un Infiltré est doué pour accéder aux endroits interdits. Il excelle à éviter la détection, à contourner les systèmes de sécurité et à récupérer des objets de valeur dans des lieux sécurisés. Dans le fracas de la guerre, la capacité à se déplacer sans être vu ni entendu lui confère un avantage crucial.',
        attrBonus:   { agility: 2, brawn: 1, coordination: 2, insight: 1 },
        skillBonus:  { athletics: 2, engineering: 1, fighting: 2, observation: 1, stealth: 2, survival: 1 },
        focusPool:   ['athletics', 'fighting', 'stealth'],
        focusCount:  2,
        talentPool:  ['acrobatic', 'assassination', 'silent_step'],
        belongings:  ['Vêtements camouflés', 'Équipement d\'escalade', 'Outils de cambriolage'],
        belongingsNote: '',
    },
    investigator: {
        label: 'Investigator',
        labelFr: 'Enquêteur',
        tagline: 'Le chercheur de vérité. Insatiable dans sa quête de la vérité, quelle qu\'en soit le prix.',
        playIf: [
            'Découvrir la vérité quoi qu\'il en coûte.',
            'Démasquer les conspirations.',
            'Fouiller les bureaux, découvrir des indices et trouver les chaînons manquants !',
        ],
        description: 'Un Enquêteur a un appétit insatiable pour la vérité et ira au bout du monde pour la trouver. Avec la propagande de guerre dominant les deux camps, la vérité est plus difficile à discerner mais plus précieuse que jamais. Enquêteurs privés, policiers militaires et journalistes plongent dans la vérité cachée derrière les gros titres.',
        attrBonus:   { agility: 1, coordination: 1, insight: 2, reason: 2 },
        skillBonus:  { academia: 2, engineering: 1, medicine: 2, observation: 2, persuasion: 1, stealth: 1 },
        focusPool:   ['academia', 'medicine', 'observation'],
        focusCount:  2,
        talentPool:  ['polymath', 'the_cutting_edge', 'detailed_analysis'],
        belongings:  [
            'Outils analytiques ou un contact (science)',
            'Kit de premiers secours ou un contact (médecine)',
            'Pistolet ou un contact (Érudition)',
        ],
        belongingsNote: 'Choisissez un kit ou un contact.',
    },
    occultist: {
        label: 'Occultist',
        labelFr: 'Occultiste',
        tagline: 'Le mystique. A plongé dans les forces plus profondes et étranges de l\'univers.',
        playIf: [
            'Posséder une connaissance étrange des rouages intimes de l\'univers.',
            'Manier une magie incroyable.',
            'Lancer des sorts, éveiller des dieux endormis, et affronter les cultistes nazis !',
        ],
        description: 'Un Occultiste a plongé dans les forces plus profondes et étranges de l\'univers, et a appris les secrets de comment les plier à sa volonté. Bien que seuls les Occultistes les plus égocentriques et délirants puissent prétendre à la maîtrise du surnaturel, même un peu de talent pour l\'ésotérique peut être précieux — ou dangereux dans les mauvaises mains.',
        attrBonus:   null, // variante A ou B
        skillBonus:  null,
        variants: {
            A: {
                label: 'Variante A — Perception dominante',
                attrBonus:  { brawn: 1, will: 2, insight: 2, reason: 1 },
                skillBonus: { observation: 1, persuasion: 2, resilience: 2, stealth: 1, academia: 2, survival: 1 },
            },
            B: {
                label: 'Variante B — Raisonnement dominant',
                attrBonus:  { brawn: 1, will: 2, insight: 1, reason: 2 },
                skillBonus: { observation: 1, persuasion: 2, resilience: 2, stealth: 1, academia: 1, survival: 2 },
            },
        },
        focusPool:   ['academia', 'persuasion', 'resilience', 'survival'],
        focusCount:  2,
        talentPool:  ['occult_scholar', 'summoner', 'a_price_to_pay'],
        talentNote:  'Un personnage ne peut avoir qu\'un seul talent avec le mot-clé Lanceur de sorts.',
        belongings:  ['Outils rituels', 'Un contact (focus Occultisme ou Mysticisme)'],
        belongingsNote: '',
    },
    soldier: {
        label: 'Soldier',
        labelFr: 'Soldat',
        tagline: 'Le combattant. Expert au combat, pour terrasser ses ennemis et protéger ses alliés.',
        playIf: [
            'Être le plus fort du groupe.',
            'Tirer de grosses armes et manier des armes brutales.',
            'Plonger à couvert, réaliser un tir impossible, ou charger vers la victoire !',
        ],
        description: 'Un Soldat excelle au combat, pour terrasser ses ennemis et protéger les autres. Même en temps de guerre, alors que des armées entières marchent à travers les villes d\'Europe, un Soldat se distingue sur le champ de bataille : il survit couramment aux horreurs et aux désastres que les autres ne peuvent surmonter, et se voit confier les missions de combat les plus spéciales.',
        attrBonus:   { agility: 1, brawn: 2, coordination: 2, insight: 1 },
        skillBonus:  { athletics: 1, fighting: 2, observation: 1, resilience: 2, survival: 2, tactics: 1 },
        focusPool:   ['fighting', 'resilience', 'survival'],
        focusCount:  2,
        talentPool:  ['army_of_one', 'draw_their_fire', 'own_the_battlefield'],
        belongings:  ['Une arme de Restriction 3 ou moins', 'Un pistolet de Restriction 1'],
        belongingsNote: '',
    },
};