// src/client/src/systems/achtung/config/backgrounds.js
// Données complètes des backgrounds (bonus attr/skill, focus, talentKeyword, équipement).
// talentKeyword est un tableau de clés anglaises (alignées sur SKILLS + 'fortune'/'weird'/'any').
// Plusieurs clés = relation "ou" : le joueur peut piocher dans le pool de n'importe laquelle.

export const BACKGROUND_DATA = {
    academic: {
        label: 'Universitaire',
        description: 'Le parcours de votre personnage est un mélange de sa formation, de sa profession et de ses expériences fondatrices. Un universitaire a consacré sa vie à l\'acquisition du savoir.',
        attrBonus:  { coordination: 2, insight: 1, reason: 2, will: 1 },
        skillBonus: { academia: 2, observation: 1, persuasion: 1 },
        focusFixed: 'academia',
        focusNote:  '1 focus en Érudition (choix libre) + 1 focus libre',
        talentKeyword: ['academia'],
        truthSuggestions: ['Docteur en (sujet)', 'Conservateur de musée', 'Professeur de (sujet)'],
        belongings: 'Un contact (Érudition)',
    },
    air_force: {
        label: 'Armée de l\'air',
        description: 'Vous avez servi dans les forces aériennes et connaissez les avions, les tactiques aériennes et la discipline militaire.',
        attrBonus:  { agility: 1, coordination: 2, insight: 2, reason: 1 },
        skillBonus: { engineering: 1, tactics: 1, vehicles: 2 },
        focusFixed: 'vehicles',
        focusNote:  '1 focus en Véhicules (choix libre) + 1 focus libre',
        talentKeyword: ['vehicles'],
        truthSuggestions: ['As de l\'aviation', 'Expert navigateur', 'Mécanicien talentueux'],
        belongings: 'Outils de mécanicien ou un contact (mécanique, véhicules lourds, ou aéronefs)',
    },
    army: {
        label: 'Armée de terre',
        description: 'Vous avez servi dans l\'armée de terre et avez reçu une formation au combat, à la tactique et à la vie en campagne.',
        attrBonus:  { agility: 2, brawn: 2, coordination: 1, will: 1 },
        skillBonus: { athletics: 1, fighting: 2, tactics: 1 },
        focusFixed: 'fighting',
        focusNote:  '1 focus en Combat (choix libre) + 1 focus libre',
        talentKeyword: ['fighting'],
        truthSuggestions: ['Tireur d\'élite', 'Parachutiste', 'Commando redoutable'],
        belongings: 'Une ceinture de munitions',
    },
    athlete: {
        label: 'Athlète',
        description: 'Vous avez consacré votre vie au sport et à la compétition, développant un physique exceptionnel et une discipline de fer.',
        attrBonus:  { agility: 2, brawn: 2, coordination: 1, insight: 1 },
        skillBonus: { athletics: 2, fighting: 1, resilience: 1 },
        focusFixed: 'athletics',
        focusNote:  '1 focus en Athlétisme (choix libre) + 1 focus libre',
        talentKeyword: ['athletics'],
        truthSuggestions: ['Champion de football', 'Champion de boxe olympique', 'Athlète professionnel'],
        belongings: 'Une batte de base-ball, une batte de cricket, ou un autre équipement sportif',
    },
    covert_operative: {
        label: 'Agent clandestin',
        description: 'Vous avez travaillé dans les opérations secrètes — espionnage, sabotage, ou résistance — avant même que la guerre ne vous entraîne dans la Guerre Secrète.',
        attrBonus:  { agility: 2, coordination: 1, insight: 1, will: 2 },
        skillBonus: { persuasion: 1, stealth: 2, tactics: 1 },
        focusFixed: 'stealth',
        focusNote:  '1 focus en Discrétion (choix libre) + 1 focus libre',
        talentKeyword: ['stealth'],
        truthSuggestions: ['Identité de couverture', 'Tueur silencieux', 'Membre de la Résistance'],
        belongings: 'Documents d\'identité et 1 arme de Restriction 2 ou moins avec silencieux',
    },
    criminal: {
        label: 'Criminel',
        description: 'Vous avez vécu en dehors de la loi, que ce soit par nécessité, par choix ou par accident. La guerre vous offre peut-être une chance de racheter votre passé — ou d\'en tirer profit.',
        attrBonus:  { agility: 2, brawn: 1, insight: 2, will: 1 },
        skillBonus: { persuasion: 2, stealth: 1, tactics: 1 },
        focusFixed: 'persuasion',
        focusNote:  '1 focus en Persuasion (choix libre) + 1 focus libre',
        talentKeyword: ['persuasion'],
        truthSuggestions: ['Escroc professionnel', 'Braqueur de banque', 'Assassin à gages'],
        belongings: 'Un objet de Restriction 2 ou moins lié à votre crime, ou de faux papiers d\'identité',
    },
    driver: {
        label: 'Chauffeur',
        description: 'Vous avez passé votre vie au volant ou dans les ateliers de mécanique, développant une maîtrise exceptionnelle des véhicules de toutes sortes.',
        attrBonus:  { brawn: 1, coordination: 2, insight: 2, reason: 1 },
        skillBonus: { athletics: 1, engineering: 1, vehicles: 2 },
        focusFixed: 'vehicles',
        focusNote:  '1 focus en Véhicules (choix libre) + 1 focus libre',
        talentKeyword: ['vehicles'],
        truthSuggestions: ['As du volant', 'Pilote de course', 'Chauffeur de maître'],
        belongings: 'Un véhicule de transport (discutez les détails avec votre MJ)',
    },
    engineer: {
        label: 'Ingénieur',
        description: 'Votre formation en ingénierie vous permet de concevoir, construire et réparer des mécanismes complexes, des fortifications aux équipements de communication.',
        attrBonus:  { agility: 1, coordination: 2, insight: 1, reason: 2 },
        skillBonus: { academia: 1, engineering: 2, observation: 1 },
        focusFixed: 'engineering',
        focusNote:  '1 focus en Ingénierie (choix libre) + 1 focus libre',
        talentKeyword: ['engineering'],
        truthSuggestions: ['Expert en explosifs', 'Génie de l\'électronique', 'Architecte militaire'],
        belongings: 'Outils d\'ingénieur et plans de base',
    },
    entertainer: {
        label: 'Artiste',
        description: 'Acteur, musicien, danseur ou acrobate — vous savez comment captiver un public et, si nécessaire, jouer un rôle pour vous fondre dans n\'importe quelle situation.',
        attrBonus:  { agility: 2, coordination: 1, insight: 1, will: 2 },
        skillBonus: { athletics: 1, observation: 1, persuasion: 2 },
        focusFixed: 'persuasion',
        focusNote:  '1 focus en Persuasion (choix libre) + 1 focus libre',
        talentKeyword: ['persuasion'],
        truthSuggestions: ['Acteur renommé', 'Musicien de jazz', 'Acrobate de cirque'],
        belongings: 'Costume ou déguisement de scène, et un instrument ou accessoire lié à votre art',
    },
    journalist: {
        label: 'Journaliste',
        description: 'Correspondant de guerre, reporter ou photographe — vous avez vu les horreurs de la guerre de près et savez comment trouver, vérifier et diffuser l\'information.',
        attrBonus:  { coordination: 1, insight: 2, reason: 1, will: 2 },
        skillBonus: { academia: 1, observation: 2, persuasion: 1 },
        focusFixed: 'observation',
        focusNote:  '1 focus en Observation (choix libre) + 1 focus libre',
        talentKeyword: ['observation'],
        truthSuggestions: ['Correspondant de guerre', 'Photographe de terrain', 'Journaliste d\'investigation'],
        belongings: 'Appareil photo, carnet de notes et accréditation de presse',
    },
    labourer: {
        label: 'Ouvrier',
        description: 'Mineur, docker, ouvrier agricole ou de chantier — vous avez forgé votre corps et votre esprit dans l\'effort physique quotidien.',
        attrBonus:  { agility: 1, brawn: 2, coordination: 2, will: 1 },
        skillBonus: { athletics: 1, resilience: 2, survival: 1 },
        focusFixed: 'resilience',
        focusNote:  '1 focus en Résilience (choix libre) + 1 focus libre',
        talentKeyword: ['resilience'],
        truthSuggestions: ['Syndicaliste engagé', 'Mineur chevronné', 'Ouvrier du chantier naval'],
        belongings: 'Outils de votre métier',
    },
    military_officer: {
        label: 'Officier militaire',
        description: 'Vous avez gravi les échelons militaires et appris à commander des hommes, à planifier des opérations et à prendre des décisions sous pression.',
        attrBonus:  { agility: 1, insight: 1, reason: 2, will: 2 },
        skillBonus: { fighting: 1, persuasion: 1, tactics: 2 },
        focusFixed: 'tactics',
        focusNote:  '1 focus en Tactique (choix libre) + 1 focus libre',
        talentKeyword: ['tactics'],
        truthSuggestions: ['Vétéran de campagne', 'Stratège brillant', 'Chef respecté'],
        belongings: 'Revolver de service et documents militaires',
    },
    navy: {
        label: 'Marine',
        description: 'Marin, sous-marinier ou officier de marine — vous connaissez la guerre sur mer et la discipline de fer de la vie à bord.',
        attrBonus:  { agility: 2, brawn: 1, coordination: 2, reason: 1 },
        skillBonus: { engineering: 1, tactics: 1, vehicles: 2 },
        focusFixed: 'vehicles',
        focusNote:  '1 focus en Véhicules (choix libre) + 1 focus libre',
        talentKeyword: ['vehicles'],
        truthSuggestions: ['Vétéran de la Bataille de l\'Atlantique', 'Sous-marinier', 'Officier de pont'],
        belongings: 'Kit de navigation et carte marine',
    },
    physician: {
        label: 'Médecin',
        description: 'Médecin, chirurgien ou psychiatre — vous avez consacré votre vie à sauver des vies, que ce soit sur le front ou à l\'arrière.',
        attrBonus:  { coordination: 2, insight: 1, reason: 2, will: 1 },
        skillBonus: { academia: 1, medicine: 2, resilience: 1 },
        focusFixed: 'medicine',
        focusNote:  '1 focus en Médecine (choix libre) + 1 focus libre',
        talentKeyword: ['medicine'],
        truthSuggestions: ['Chirurgien de guerre', 'Psychiatre militaire', 'Médecin de campagne'],
        belongings: 'Trousse médicale complète',
    },
    police: {
        label: 'Police',
        description: 'Inspecteur, agent ou gendarme — vous avez l\'œil exercé pour observer, déduire et agir dans des situations dangereuses.',
        attrBonus:  { agility: 1, brawn: 1, coordination: 2, insight: 2 },
        skillBonus: { fighting: 1, observation: 2, persuasion: 1 },
        focusFixed: 'observation',
        focusNote:  '1 focus en Observation (choix libre) + 1 focus libre',
        talentKeyword: ['observation'],
        truthSuggestions: ['Inspecteur chevronné', 'Agent de la criminelle', 'Gendarme de campagne'],
        belongings: 'Badge et pistolet de service',
    },
    politician: {
        label: 'Politicien',
        description: 'Député, diplomate ou fonctionnaire — vous maîtrisez l\'art de la négociation, du discours et des coulisses du pouvoir.',
        attrBonus:  { coordination: 1, insight: 2, reason: 1, will: 2 },
        skillBonus: { academia: 1, persuasion: 2, tactics: 1 },
        focusFixed: 'persuasion',
        focusNote:  '1 focus en Persuasion (choix libre) + 1 focus libre',
        talentKeyword: ['persuasion'],
        truthSuggestions: ['Député respecté', 'Diplomate chevronné', 'Homme de l\'ombre'],
        belongings: 'Documents officiels et contacts gouvernementaux',
    },
    resistance: {
        label: 'Résistance',
        description: 'Vous avez rejoint les réseaux de résistance clandestins, risquant votre vie pour saboter l\'occupant et aider les Alliés.',
        attrBonus:  { agility: 1, coordination: 1, reason: 2, will: 2 },
        skillBonus: { persuasion: 1, stealth: 2, tactics: 1 },
        focusFixed: 'stealth',
        focusNote:  '1 focus en Discrétion (choix libre) + 1 focus libre',
        talentKeyword: ['stealth'],
        truthSuggestions: ['Agent de liaison allié', 'Saboteur ferroviaire', 'Passeur de la ligne de démarcation'],
        belongings: 'Faux papiers et cache de matériel',
    },
    spiritual_leader: {
        label: 'Guide spirituel',
        description: 'Prêtre, pasteur, rabbin ou autre figure spirituelle — vous guidez les âmes en ces temps d\'obscurité et avez peut-être été confronté à des vérités plus terrifiantes que le péché ordinaire.',
        attrBonus:  { agility: 1, insight: 2, reason: 1, will: 2 },
        skillBonus: { academia: 2, persuasion: 1, resilience: 1 },
        focusFixed: 'academia',
        focusNote:  '1 focus en Érudition (choix libre) + 1 focus libre',
        talentKeyword: ['academia'],
        truthSuggestions: ['Aumônier militaire', 'Érudit des textes anciens', 'Mystique'],
        belongings: 'Textes sacrés et vêtements liturgiques',
    },
    veteran_great_war: {
        label: 'Vétéran de la Grande Guerre',
        description: 'Vous avez combattu dans la Première Guerre Mondiale, pensant que c\'était "la guerre pour en finir avec toutes les guerres". Maintenant, un autre conflit mondial fait rage et vous rappelez les vieilles compétences.',
        attrBonus:  { brawn: 1, coordination: 1, will: 1 },
        skillBonus: { fighting: 1, survival: 1 },
        skillBonusFree: 2, // +1 à 2 compétences libres
        focusFixed: null,
        focusNote:  '1 focus en Combat ou Survie + 1 focus libre',
        focusFixedChoice: ['fighting', 'survival'],
        talentKeyword: ['fighting', 'survival'],
        truthSuggestions: ['Vétéran des tranchées', 'Survivant de la Somme', 'Ancien combattant de 14-18'],
        belongings: 'Un vieux revolver de service (Enfield Service Revolver)',
    },
    wanted: {
        label: 'Recherché par les autorités',
        description: 'Vous avez commis un crime grave, étiez traqué par les autorités, mais vous avez trouvé moyen de vous rendre utile — et peut-être de vous racheter. Ou pas.',
        attrBonus:  { agility: 1, insight: 1 },
        attrBonusFree: 1,
        skillBonus: { persuasion: 1, stealth: 1 },
        skillBonusFree: 2,
        focusFixed: null,
        focusNote:  '1 focus en Persuasion ou Discrétion + 1 focus libre',
        focusFixedChoice: ['persuasion', 'stealth'],
        talentKeyword: ['persuasion', 'stealth'],
        truthSuggestions: ['Fugitif recherché', 'Passé criminel sombre', 'Identité empruntée'],
        belongings: 'Un objet de Restriction 2 ou moins lié à votre crime, ou de faux papiers d\'identité',
    },
};