// src/client/src/systems/achtung/config/characteristics.js
// Données complètes des caractéristiques (bonus attr/skill, focus, talentKeyword, équipement).
// talentKeyword est un tableau de clés anglaises (alignées sur SKILLS + 'fortune'/'weird'/'any').
// Plusieurs clés = relation "ou" : le joueur peut piocher dans le pool de n'importe laquelle.
// wanted_young_at_heart utilise isChoice + options{} (cas particulier, conservé tel quel).

export const CHARACTERISTIC_DATA = {
    bookworm: {
        label: 'Rat de bibliothèque',
        description: 'Vous avez étudié avec intensité et avez un amour profond de l\'apprentissage et du savoir. Vous connaissez des faits obscurs et des statistiques étranges, et vous préféreriez passer votre temps libre le nez dans un livre.',
        attrBonus:  { insight: 1, reason: 1 },
        attrBonusFree: 1,
        skillBonus: { academia: 1 },
        skillBonusFree: 3, // +1 à 3 autres compétences (no duplicate)
        talentKeyword: ['academia'],
        truthDefault: 'Rat de bibliothèque',
        belongings: 'Des livres et journaux liés à votre domaine d\'étude',
    },
    born_behind_wheel: {
        label: 'Né derrière un volant',
        description: 'Vous vivez à bord de véhicules, ou enfoncé dans les rouages de vos engins favoris. Vous pouvez réparer ou conduire presque n\'importe quoi.',
        attrBonus:  { coordination: 1, reason: 1 },
        attrBonusFree: 1,
        skillBonus: { engineering: 1, vehicles: 1 },
        skillBonusFree: 2,
        talentKeyword: ['vehicles'],
        truthDefault: 'Né derrière un volant',
        belongings: 'Une salopette, des gants de conduite et des lunettes.',
    },
    built_brick_outhouse: {
        label: 'Bâti comme une armoire',
        description: 'Vous êtes immense. Vous dominez de la tête ceux qui vous entourent, et votre taille n\'est pas seulement physique — vous êtes fort et vous avez toujours trouvé des façons de mettre cette force à profit.',
        attrBonus:  { brawn: 1, coordination: 1 },
        attrBonusFree: 1,
        skillBonus: { athletics: 1, fighting: 1, resilience: 1 },
        skillBonusFree: 1,
        talentKeyword: ['athletics', 'resilience'],
        truthDefault: 'Bâti comme une armoire',
        belongings: 'Vos vêtements sont soit trop petits, soit lourdement modifiés pour accommoder votre taille inhabituele.',
    },
    conscientious_objector: {
        label: 'Objecteur de conscience',
        description: 'La violence n\'est jamais la réponse — mais ça ne fait pas de vous un lâche. De nombreux objecteurs de conscience servent avec distinction dans des rôles variés et apportent une réelle contribution à l\'effort de guerre. L\'exposition à la Guerre Secrète va tester vos idéaux jusqu\'à leurs limites absolues.',
        attrBonus:  { reason: 1, will: 1 },
        attrBonusFree: 1,
        skillBonus: { resilience: 1 },
        skillBonusFree: 3, // pas Combat ni Tactique, no duplicate
        skillExclude: ['fighting', 'tactics'],
        talentKeyword: ['resilience'],
        truthDefault: 'Objecteur de conscience',
        belongings: 'Un kit de compétence pour une compétence avec un rang de 2+',
    },
    criminal_mindset: {
        label: 'Esprit criminel',
        description: 'Vous vivez en dehors des petites considérations de la loi et il y a toujours une opportunité à saisir. Comme il y a toujours des excuses pour vos actes. Mais peut-être que vos compétences uniques peuvent être d\'une utilité dans la Guerre Secrète ?',
        attrBonus:  { insight: 1, agility: 1 },
        attrBonusFree: 1,
        skillBonus: { observation: 1, stealth: 1 },
        skillBonusFree: 2,
        talentKeyword: ['stealth', 'persuasion'],
        truthDefault: 'Esprit criminel',
        belongings: 'Un seul objet de Restriction 3 ou moins, obtenu illégalement.',
    },
    dilettante: {
        label: 'Dilettante',
        description: 'Vous êtes un touche-à-tout et pouvez vous en sortir avec à peu près n\'importe quoi avec un certain degré de succès — même si vous êtes vite prêt à passer à autre chose.',
        attrBonus:  { coordination: 1, insight: 1 },
        attrBonusFree: 1,
        skillBonus: {}, // +1 à TOUTES les compétences à 0
        specialRule: 'dilettante', // gain +1 to every skill currently at 0
        talentKeyword: ['any'],
        truthDefault: 'Dilettante',
        belongings: 'Plusieurs objets triviaux potentiellement utiles (montre de poche, tournevis, allumettes, etc.) déclarables à votre discrétion au fil du jeu.',
    },
    dreamwalker: {
        label: 'Marcheur de rêves',
        description: 'Le sommeil n\'est qu\'un passage et, même enfant, vous vous êtes aventuré dans les Contrées du Rêve. De nombreux êtres étranges ont tenté de vous piéger pour vous faire obéir, mais vous avez évité ces destins oubliés. Maintenant votre pays a besoin de vous — pouvez-vous utiliser la sagesse particulière que vous avez gagnée à contempler le grand au-delà ?',
        attrBonus:  { insight: 1, will: 1 },
        attrBonusFree: 1,
        skillBonus: { resilience: 1, observation: 1 },
        skillBonusFree: 2,
        talentKeyword: ['observation', 'weird'],
        truthDefault: 'Marcheur de rêves',
        belongings: 'Un animal familier de votre choix, dévoué et semblant percevoir des choses que les autres ne voient pas.',
    },
    escaped_europe: {
        label: 'Évadé d\'Europe',
        description: 'Tout ce que vous aimiez autrefois a été englouti par la machine de guerre allemande et ses terribles maîtres. Vous avez combattu dur et donné le meilleur de vous-même, mais avez finalement dû fuir pour ne pas mourir. Votre nouvelle maison vous semble étrange, mais en travaillant avec les Alliés vous brûlez du désir de libérer votre patrie.',
        attrBonus:  { insight: 1, will: 1 },
        attrBonusFree: 1,
        skillBonus: { academia: 1, athletics: 1, persuasion: 1, survival: 1 },
        talentKeyword: ['persuasion', 'survival'],
        truthDefault: 'Évadé d\'Europe',
        belongings: 'Un seul objet personnel précieux de votre foyer perdu.',
    },
    experimental_subject: {
        label: 'Sujet d\'expérience',
        description: 'L\'effort de guerre a besoin de volontaires pour apprendre exactement ce qui peut être accompli par la science, la technologie et même les forces mystiques. Des expériences top secrètes hors-livre sont menées pour améliorer les soldats avec de nouveaux pouvoirs effrayants. Vous vous êtes porté volontaire. Vraiment ? Enfin, c\'est courant en ces temps extraordinaires.',
        attrBonus:  { agility: 1, brawn: 1 },
        attrBonusFree: 1,
        skillBonusFree: 4, // +1 à 4 compétences (no duplicate)
        talentKeyword: ['weird'],
        truthDefault: 'Sujet d\'expérience',
        belongings: 'Une forme d\'identification étrange, des sigils ou des marques mystérieuses sur la peau, peut-être des documents incomplets, ou un uniforme étrange rappelant votre période de test.',
    },
    my_war_started_early: {
        label: 'Ma guerre a commencé tôt',
        description: 'Que vous ayez commencé à vous battre en Abyssinie, en Tchécoslovaquie, en Mandchourie, ou en Espagne, vous étiez en guerre bien avant que le conflit principal n\'éclate. La guerre est une horreur, mais pour vous elle est devenue presque banalement quotidienne.',
        attrBonus:  { agility: 1, brawn: 1, coordination: 1 },
        skillBonus: { fighting: 1, medicine: 1 },
        skillBonusFree: 2,
        talentKeyword: ['fighting', 'medicine'],
        truthDefault: 'Ma guerre a commencé tôt',
        belongings: 'Quelques souvenirs précieux, comme une photo de famille, la montre de votre père, ou un objet culturel ou religieux que vous portez toujours.',
    },
    nomadic: {
        label: 'Nomade',
        description: 'Autrefois vous aviez un foyer, mais maintenant la route est votre maison. Vous êtes un esprit agité et ne restez jamais trop longtemps au même endroit. Vous avez toujours gardé une longueur d\'avance sur vos ennuis, et avez appris à apprécier la liberté qu\'offre un mode de vie itinérant.',
        attrBonus:  { brawn: 1, coordination: 1, reason: 1 },
        skillBonus: { survival: 1, vehicles: 1 },
        skillBonusFree: 2,
        talentKeyword: ['survival', 'vehicles'],
        truthDefault: 'Nomade',
        belongings: 'Quelques objets pratiques (canif, dés, ficelle) et de quoi vous tirer d\'affaire, comme un instrument ou un jeu de cartes.',
    },
    own_occult_artefact: {
        label: 'Possesseur d\'artefact occulte',
        description: 'Il est dans votre famille depuis aussi longtemps que vous vous en souvenez et maintenant sa garde vous incombe. Que ce soit une arme capable d\'être retournée contre le Reich, l\'âme d\'un monstre piégé, ou un fragment d\'une entité pickled pour la postérité, vous devez décider comment vous allez utiliser cet étrange artefact.',
        attrBonus:  { reason: 1, will: 1 },
        attrBonusFree: 1,
        skillBonus: { resilience: 1 },
        skillBonusFree: 3, // +1 à Observation, Persuasion ou Discrétion + +1 à 2 autres (no duplicate)
        skillBonusChoice: ['observation', 'persuasion', 'stealth'], // choisir 1 parmi
        talentKeyword: ['weird'],
        truthDefault: 'Possesseur d\'artefact occulte',
        belongings: 'Un artefact occulte (tome des Mythes de Cthulhu, jeton d\'une divinité, miroir de scrutation d\'obsidienne, ou boîte mystérieuse qui chuchote dans votre sommeil — à définir avec le MJ).',
    },
    raised_by_cult: {
        label: 'Élevé dans une secte',
        description: 'Vous êtes né et avez grandi dans un ordre ésotérique secret. Le dimanche, pendant que les autres allaient à l\'église et chantaient des hymnes, votre famille célébrait sous les étoiles avec d\'autres, des rites plus sombres et plus anciens. Vous avez vu des choses horribles et stupéfiantes, élargissant votre esprit et vous donnant une nouvelle perspective sur la place de l\'homme dans l\'univers.',
        attrBonus:  { brawn: 1, insight: 1 },
        attrBonusFree: 1,
        skillBonus: { academia: 1, resilience: 1, stealth: 1 },
        skillBonusFree: 1,
        talentKeyword: ['stealth', 'resilience', 'weird'],
        truthDefault: 'Élevé dans une secte',
        belongings: 'Robes cérémoniales, jetons, charmes et autres accessoires personnels de la secte.',
    },
    raised_colonies: {
        label: 'Élevé dans les colonies',
        description: 'Lorsque la guerre est venue en Europe, vous étiez loin du front. Peu de pays étaient aussi éloignés de l\'action que le vôtre, mais vous avez quand même signé pour le roi et le pays et avez voyagé des milliers de kilomètres pour aider l\'effort de guerre. Le vôtre était une existence rurale où l\'agriculture était primordiale, le bétail paissait dans les plaines et tout le monde se connaissait.',
        attrBonus:  { agility: 1, brawn: 1, will: 1 },
        skillBonus: { athletics: 1, survival: 1 },
        skillBonusFree: 2,
        talentKeyword: ['athletics', 'survival'],
        truthDefault: 'Élevé dans les colonies',
        belongings: 'Quelques vêtements ou objets personnels de votre nation natale.',
    },
    read_occult_book: {
        label: 'A lu un grimoire maudit',
        description: 'À un moment de votre passé, vous avez lu un livre interdit, qui révélait des secrets horrifiques et les étranges mystères de l\'univers. Vous ne vous souvenez pas exactement de ce que vous avez lu, mais la sensation d\'avoir vu ces sigils et ces mots reste présente, comme une pâle cicatrice sur l\'esprit.',
        attrBonus:  { insight: 1, will: 1 },
        attrBonusFree: 1,
        skillBonus: { observation: 1, resilience: 1 },
        skillBonusFree: 2,
        talentKeyword: ['weird'],
        truthDefault: 'A lu un grimoire maudit',
        belongings: 'Une collection de notes personnelles tirées d\'un tome occulte.',
    },
    scientific_visionary: {
        label: 'Visionnaire scientifique',
        description: 'Vous avez fait une découverte incroyable grâce à vos études, qui peut s\'avérer une précieuse contribution à l\'effort de guerre.',
        attrBonus:  { insight: 1, reason: 1 },
        attrBonusFree: 1,
        skillBonus: { academia: 1, engineering: 1 },
        skillBonusFree: 2,
        talentKeyword: ['academia', 'engineering'],
        truthDefault: 'Visionnaire scientifique',
        belongings: 'Un contact avec l\'un des focuses suivants : cryptographie, science, électronique, explosifs, ou la compétence Médecine.',
    },
    street_kid: {
        label: 'Enfant des rues',
        description: 'Votre vie jusqu\'à présent a été dure, et vous avez dû travailler dur pour le peu que vous avez. D\'une façon ou d\'une autre vous avez toujours réussi à vous en sortir. Vous êtes rapide, vous êtes coriace, et vous êtes malin, et vous comptez sur vos ruses et vos instincts de rue pour survivre.',
        attrBonus:  { brawn: 1, coordination: 1, reason: 1 },
        skillBonus: { resilience: 1, survival: 1, stealth: 1 },
        skillBonusFree: 1,
        talentKeyword: ['survival'],
        truthDefault: 'Enfant des rues',
        belongings: 'Un porte-bonheur ou un autre symbole de bonne fortune.',
    },
    the_lucky_one: {
        label: 'Le miraculé',
        description: 'Quand l\'ordre de se mettre à l\'abri est arrivé, vous y avez obéi à la lettre. Puis la bombe est tombée et vous étiez le seul survivant. Vous ne pouvez pas expliquer comment vous avez tenu quand tous les autres sont morts, mais vous les entendez maintenant vous chuchoter dans le dos, vous traitant de Jonah et insinuant que vous portez la poisse.',
        attrBonus:  { agility: 1, brawn: 1, will: 1 },
        skillBonus: { athletics: 1, tactics: 1 },
        skillBonusFree: 2,
        talentKeyword: ['fortune'],
        truthDefault: 'Le miraculé',
        belongings: 'Un souvenir poignant d\'un de vos amis ou camarades tombés.',
    },
    veteran_great_war: {
        label: 'Vétéran de la Grande Guerre (Caractéristique)',
        description: 'Vous avez combattu dans la Première Guerre Mondiale. Maintenant une autre guerre mondiale fait rage, rappelant d\'anciennes compétences et de vieux cauchemars.',
        attrBonus:  { brawn: 1, coordination: 1, will: 1 },
        skillBonus: { fighting: 1, survival: 1 },
        skillBonusFree: 2,
        talentKeyword: ['fighting', 'survival'],
        truthDefault: 'Vétéran de la Grande Guerre',
        belongings: 'Un vieux revolver de service.',
    },
    wanted_young_at_heart: {
        label: 'Recherché / Jeune de cœur',
        description: 'Deux options au choix — Recherché par les Autorités : vous avez commis un crime grave et étiez en fuite. Jeune de Cœur : vous êtes peut-être jeune ou simplement naïf, mais quand ça compte vous absorbez ce dont vous avez besoin à une vitesse remarquable.',
        isChoice: true,
        options: {
            wanted: {
                label: 'Recherché par les autorités',
                attrBonus:  { agility: 1, insight: 1 },
                attrBonusFree: 1,
                skillBonus: { persuasion: 1, stealth: 1 },
                skillBonusFree: 2,
                talentKeyword: ['persuasion', 'stealth'],
                truthDefault: 'Recherché',
                belongings: 'Un objet de Restriction 2 ou moins lié à votre crime, ou de faux papiers.',
            },
            young_at_heart: {
                label: 'Jeune de cœur',
                attrBonus:  { agility: 1, reason: 1 },
                attrBonusFree: 1,
                skillBonus: { athletics: 1, stealth: 1 },
                skillBonusFree: 2, // +2 à n'importe quelle compétence avec rang 0 ou 1
                talentKeyword: ['any'],
                truthDefault: 'Jeune de cœur',
                belongings: '1 ressource supplémentaire pour chaque kit de compétence que vous possédez.',
            },
        },
    },
};